apiVersion: v1
kind: Service
metadata:
  name: bagginsdb
  labels:
    app: bagginsdb
spec:
  clusterIP: None # Headless service for StatefulSet
  ports:
    - port: 50051
      name: grpc
  selector:
    app: bagginsdb
