apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bagginsdb
  labels:
    app: bagginsdb
spec:
  serviceName: "bagginsdb" # Must match the headless service name
  replicas: 3
  selector:
    matchLabels:
      app: bagginsdb
  template:
    metadata:
      labels:
        app: bagginsdb
    spec:
      containers:
        - name: bagginsdb
          image: bagginsdb:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50051
              name: grpc
          env:
            # NODE_ID is set from the pod name.
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            # All nodes use the first pod as the seed.
            - name: SEED_NODE_ADDRESS
              value: "bagginsdb-0.bagginsdb.default.svc.cluster.local:50051"
