global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "bagginsdb"
    static_configs:
      - targets: ["host.docker.internal:9092"] # The address where your Go app is exposing /metrics

remote_write:
  - url: "https://prometheus-prod-24-prod-eu-west-2.grafana.net/api/prom/push"
    basic_auth:
      username: "1971290"
      password: ""
